### ISSUE TITLE
Dynamic value support

### ISSUE THREAD

**Issue by MatanYadaev** [envant/fireable#11]
Current state works good for statuses, what about numeric/dynamic fields?
I want to dispatch an event when a user passing 50 points.

```php

class User extends Model
{
    use FireableAttributes;

    protected $fillable = [
        'points',
    ];

    protected function getFireableAttributes() : array
    {
        return [
            'points' => [
                UserPassed50Points::class => static function (User $user) {
                    return $user->points >= 50;
                },
            ],
        ];
    }
}
```

The implementation is a bit problematic, because it requires to use a method and not a property, as well it's moving the event name to the key and the closure to the value.

**Comment by lepikhinb** [comment]
I'm not sure it's a good idea to put the logic here, instead I'd propose you to fire corresponding events from a separated event / listener.

However I'll try to figure out if we can do something (though you can't use callbacks in model properties).

**Comment by franksteinberg** [comment]
@MatanYadaev -
While I like the idea, you might be best off firing a `ScoredPoints` event, and have a listener specifically for your points threshold, `Passed50Points`. Then in the Listener, you can use the `shouldQueue()` method:

```

public function shouldQueue(ScoredPoints $event)
{
    return $event->user->score >= 50;
}

```

I hope this is helpful.
