### ISSUE TITLE
Laravel 10 & PHP 8.1

### ISSUE THREAD

**Issue by heikokrebs** [envant/fireable#25]
Hey!

I would like to use this with a Laravel 10 app. Is it possible to tag a release for Laravel 10?

**Comment by thijskok** [comment]
Just a friendly ping, @lepikhinb . We're also looking forward to upgrading to Laravel 10. There's a PR (#24) ready and waiting 👍

**Comment by lepikhinb** [comment]
@thijskok sorry for the delay! Just tagged an update

**Comment by thijskok** [comment]
> @thijskok sorry for the delay! Just tagged an update

No apology necessary! Thank you for tagging the update, much appreciated 👍
